# Generated by Django 2.2.3 on 2019-07-16 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('amount_available', models.IntegerField()),
                ('product_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('shipping_address', models.CharField(choices=[('YDE', 'YAOUNDE'), ('DLA', 'DOUALA'), ('BSA', 'BAFOUSSAM'), ('EBW', 'EBOLOWA'), ('MRA', 'MAROUA'), ('GRA', 'GAROUA'), ('BUA', 'BUEA'), ('BDA', 'BAMENDA'), ('NDR', 'NGAOUNDERE'), ('BTA', 'BERTOUA')], max_length=20)),
                ('payment_type', models.CharField(choices=[('M', 'Mtn Mobile Money'), ('L', 'A la livraison')], default='L', max_length=20)),
                ('status', models.CharField(choices=[('HO', 'on hold'), ('CA', 'canceled'), ('CO', 'Completed')], default='HO', max_length=20)),
                ('shipping_cost', models.IntegerField()),
                ('total', models.IntegerField()),
                ('products_list', models.ManyToManyField(to='home.Product')),
            ],
        ),
    ]
